<?php
declare(strict_types=1);
require dirname(__DIR__) . '/app/Bootstrap.php';
$user = App::requireAuth();
if (($user['role'] ?? '') !== 'general-manager') { http_response_code(403); exit('الفحص متاح للمدير العام فقط.'); }
$db = App::db();
$driver = App::env('DB_CONNECTION','mysql') === 'sqlite' ? 'sqlite' : 'mysql';
$results = [];
function qaAdd(array &$results,string $group,string $name,string $status,string $detail): void {$results[]=['group'=>$group,'name'=>$name,'status'=>$status,'detail'=>$detail];}
function qaTableExists(PDO $db,string $driver,string $table): bool {
    if($driver==='sqlite'){$q=$db->prepare("SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name=?");$q->execute([$table]);}
    else{$q=$db->prepare('SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name=?');$q->execute([$table]);}
    return (bool)$q->fetchColumn();
}
function qaCount(PDO $db,string $sql): int {return (int)$db->query($sql)->fetchColumn();}
function qaSafe(array &$results,string $group,string $name,callable $check): void {try{[$status,$detail]=$check();qaAdd($results,$group,$name,$status,$detail);}catch(Throwable $e){qaAdd($results,$group,$name,'fail','تعذر الفحص: '.$e->getMessage());}}

qaAdd($results,'النظام','الاتصال بقاعدة البيانات','pass','متصل — '.$driver);
$version=trim((string)@file_get_contents(dirname(__DIR__).'/VERSION'));qaAdd($results,'النظام','إصدار الملفات',$version==='1.10.0-server'?'pass':'warn',$version?:'غير معروف');
qaAdd($results,'النظام','بيئة الإنتاج',App::env('APP_ENV','production')==='production'?'pass':'warn',App::env('APP_ENV','غير محددة'));
qaAdd($results,'النظام','رابط النظام للبريد',App::env('APP_URL','')?'pass':'warn',App::env('APP_URL','')?:'أضف APP_URL إلى .env لضمان صحة رابط الاستعادة');
qaAdd($results,'النظام','مرسل بريد الاستعادة',App::env('MAIL_FROM_ADDRESS','')?'pass':'warn',App::env('MAIL_FROM_ADDRESS','')?:'أضف MAIL_FROM_ADDRESS وتأكد من إعداد mail() في الاستضافة');
qaAdd($results,'النظام','مجلد التخزين',is_writable(dirname(__DIR__).'/storage')?'pass':'fail',is_writable(dirname(__DIR__).'/storage')?'قابل للكتابة':'غير قابل للكتابة');
$https=(!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off')||strtolower((string)($_SERVER['HTTP_X_FORWARDED_PROTO']??''))==='https';qaAdd($results,'الأمان','اتصال HTTPS',$https?'pass':'fail',$https?'مفعّل':'غير مكتشف');
qaAdd($results,'الأمان','ملف التثبيت',is_file(__DIR__.'/install.php')?'warn':'pass',is_file(__DIR__.'/install.php')?'يفضل حذفه بعد اكتمال التثبيت':'محذوف');
qaAdd($results,'الأمان','ملف الترقية',is_file(__DIR__.'/upgrade.php')?'warn':'pass',is_file(__DIR__.'/upgrade.php')?'احذفه بعد اكتمال الفحص':'محذوف');

$requiredTables=['users','projects','employees','roles','permissions','user_employee_links','password_reset_tokens','employee_contracts','attendance_records','geofences','payroll_runs','payroll_items','warehouses','warehouse_stock','warehouse_user_scopes','purchase_requests','purchase_orders','requests_for_quotation','supplier_quotations','goods_receipts','inventory_transactions','supplier_invoices','three_way_matches','supplier_payments','equipment_transfers','maintenance_work_orders','maintenance_work_logs','quality_inspections','non_conformance_reports','safety_work_permits','safety_incidents','stop_work_orders','safety_toolbox_talks','project_correspondence','documents','customers','customer_contracts','customer_claims','tax_invoices','customer_collections','subcontracts','subcontract_claims','project_budgets','project_budget_lines','project_progress_updates','project_change_orders','project_contract_claims','project_cashflow_forecasts','project_risks','journal_entries','journal_entry_lines','journal_reversals','fiscal_periods','vat_returns','tax_adjustments','withholding_tax_entries','zatca_invoice_checks','audit_logs','schema_migrations'];
$missing=[];foreach($requiredTables as $table)if(!qaTableExists($db,$driver,$table))$missing[]=$table;qaAdd($results,'قاعدة البيانات','الجداول المطلوبة',$missing?'fail':'pass',$missing?'مفقود: '.implode(', ',$missing):count($requiredTables).' جدولًا موجودًا');
$requiredMigrations=['2026_07_20_001_initial','2026_07_20_002_core_hr','2026_07_20_003_attendance_payroll','2026_07_20_004_supply_assets','2026_07_20_005_contracts_revenue','2026_07_20_006_project_controls','2026_07_20_007_procurement_match','2026_07_20_008_operations_compliance','2026_07_20_009_finance_tax','2026_07_20_010_employee_identity_access','2026_07_21_011_employee_edit_permissions'];
if(qaTableExists($db,$driver,'schema_migrations')){$q=$db->query('SELECT version FROM schema_migrations');$applied=$q->fetchAll(PDO::FETCH_COLUMN);$missingM=array_values(array_diff($requiredMigrations,$applied));qaAdd($results,'قاعدة البيانات','ترحيلات 1.1–1.10',$missingM?'fail':'pass',$missingM?'غير مطبق: '.implode(', ',$missingM):'جميع الترحيلات مطبقة');}

if(qaTableExists($db,$driver,'permissions'))qaSafe($results,'الصلاحيات','صلاحيات إدارة الموظفين',function()use($db){$keys=['hr.employee.create','hr.employee.update','hr.employee.account.manage'];$q=$db->query("SELECT permission_key FROM permissions WHERE permission_key IN ('hr.employee.create','hr.employee.update','hr.employee.account.manage')");$found=$q->fetchAll(PDO::FETCH_COLUMN);$missing=array_values(array_diff($keys,$found));return[$missing?'fail':'pass',$missing?'مفقود: '.implode(', ',$missing):'صلاحيات الإنشاء والتعديل والحسابات موجودة'];});

if(qaTableExists($db,$driver,'journal_entries')&&qaTableExists($db,$driver,'journal_entry_lines'))qaSafe($results,'المحاسبة','توازن القيود المرحلة',function()use($db){$n=qaCount($db,"SELECT COUNT(*) FROM (SELECT je.id FROM journal_entries je JOIN journal_entry_lines jl ON jl.journal_entry_id=je.id WHERE je.status='posted' GROUP BY je.id HAVING ABS(SUM(jl.debit)-SUM(jl.credit))>0.01) x");return[$n?'fail':'pass',$n?$n.' قيد غير متوازن':'جميع القيود المرحلة متوازنة'];});
if(qaTableExists($db,$driver,'warehouse_stock'))qaSafe($results,'المخزون','الأرصدة السالبة',function()use($db){$n=qaCount($db,'SELECT COUNT(*) FROM warehouse_stock WHERE on_hand<0 OR reserved_qty<0 OR reserved_qty>on_hand');return[$n?'fail':'pass',$n?$n.' رصيد يحتاج مراجعة':'لا توجد أرصدة سالبة أو حجز زائد'];});
if(qaTableExists($db,$driver,'goods_receipts')&&qaTableExists($db,$driver,'goods_receipt_lines'))qaSafe($results,'المخزون','الاستلامات المعلقة',function()use($db){$n=qaCount($db,"SELECT COUNT(*) FROM goods_receipts WHERE inspection_status='pending'");return[$n?'warn':'pass',$n?$n.' محضر بانتظار الفحص':'لا توجد استلامات معلقة'];});
if(qaTableExists($db,$driver,'supplier_invoices'))qaSafe($results,'المشتريات','فواتير معتمدة دون مطابقة',function()use($db){$n=qaCount($db,"SELECT COUNT(*) FROM supplier_invoices WHERE status IN ('approved','partially_paid','paid') AND match_status<>'matched'");return[$n?'fail':'pass',$n?$n.' فاتورة تحتاج مراجعة':'كل الفواتير المعتمدة اجتازت المطابقة الثلاثية'];});
if(qaTableExists($db,$driver,'supplier_invoices'))qaSafe($results,'المشتريات','السداد الزائد للموردين',function()use($db){$n=qaCount($db,'SELECT COUNT(*) FROM supplier_invoices WHERE paid_amount>total_amount+0.01');return[$n?'fail':'pass',$n?$n.' فاتورة مسددة بأكثر من قيمتها':'لا يوجد سداد يتجاوز قيمة الفاتورة'];});
if(qaTableExists($db,$driver,'three_way_matches'))qaSafe($results,'المشتريات','سلامة نتائج المطابقة',function()use($db){$n=qaCount($db,"SELECT COUNT(*) FROM three_way_matches WHERE status='matched' AND (ABS(value_variance)>0.01 OR ABS(quantity_variance)>0.001)");return[$n?'fail':'pass',$n?$n.' نتيجة مطابقة غير سليمة':'نتائج المطابقة المتطابقة بلا فروقات'];});
if(qaTableExists($db,$driver,'maintenance_work_orders')&&qaTableExists($db,$driver,'equipment'))qaSafe($results,'الصيانة','اتساق حالة المعدات',function()use($db){$n=qaCount($db,"SELECT COUNT(*) FROM maintenance_work_orders wo JOIN equipment e ON e.id=wo.equipment_id WHERE wo.status<>'closed' AND e.status<>'maintenance'");return[$n?'fail':'pass',$n?$n.' أمر مفتوح ومعدته ليست بحالة صيانة':'كل أوامر الصيانة المفتوحة مرتبطة بمعدات متوقفة'];});
if(qaTableExists($db,$driver,'non_conformance_reports'))qaSafe($results,'الجودة','إغلاق NCR دون تحقق مستقل',function()use($db){$n=qaCount($db,"SELECT COUNT(*) FROM non_conformance_reports WHERE status='closed' AND (verified_by IS NULL OR verified_by=action_by)");return[$n?'fail':'pass',$n?$n.' حالة إغلاق تحتاج مراجعة':'كل حالات عدم المطابقة المغلقة متحققة بصورة مستقلة'];});
if(qaTableExists($db,$driver,'stop_work_orders'))qaSafe($results,'السلامة','استئناف دون إجراء تصحيحي',function()use($db){$n=qaCount($db,"SELECT COUNT(*) FROM stop_work_orders WHERE status='resumed' AND (corrective_action IS NULL OR corrective_action='')");return[$n?'fail':'pass',$n?$n.' أمر إيقاف مستأنف دون تصحيح':'كل أوامر الاستئناف موثقة بإجراء تصحيحي'];});
if(qaTableExists($db,$driver,'safety_work_permits'))qaSafe($results,'السلامة','تصاريح منتهية ما زالت نشطة',function()use($db){$n=qaCount($db,"SELECT COUNT(*) FROM safety_work_permits WHERE status='active' AND valid_until<CURRENT_TIMESTAMP");return[$n?'warn':'pass',$n?$n.' تصريح منتهي يحتاج إغلاقًا':'لا توجد تصاريح نشطة منتهية'];});
if(qaTableExists($db,$driver,'documents'))qaSafe($results,'الوثائق','مستندات معتمدة دون معتمد',function()use($db){$n=qaCount($db,"SELECT COUNT(*) FROM documents WHERE status='approved' AND approved_by IS NULL");return[$n?'fail':'pass',$n?$n.' مستند معتمد بلا هوية معتمد':'كل المستندات المعتمدة موثقة'];});
if(qaTableExists($db,$driver,'fiscal_periods')&&qaTableExists($db,$driver,'journal_entries'))qaSafe($results,'المحاسبة','قيود مسودة داخل فترات مقفلة',function()use($db){$n=qaCount($db,"SELECT COUNT(*) FROM journal_entries je JOIN fiscal_periods fp ON je.entry_date BETWEEN fp.starts_on AND fp.ends_on WHERE fp.status='closed' AND je.status<>'posted'");return[$n?'fail':'pass',$n?$n.' قيد يخالف الإقفال':'لا توجد قيود مسودة داخل فترات مقفلة'];});
if(qaTableExists($db,$driver,'journal_reversals'))qaSafe($results,'المحاسبة','سلامة روابط القيود العكسية',function()use($db){$n=qaCount($db,"SELECT COUNT(*) FROM journal_reversals jr LEFT JOIN journal_entries o ON o.id=jr.original_entry_id LEFT JOIN journal_entries r ON r.id=jr.reversal_entry_id WHERE o.status<>'posted' OR r.status<>'posted'");return[$n?'fail':'pass',$n?$n.' رابط عكس غير سليم':'كل القيود العكسية مرتبطة بقيود مرحلة'];});
if(qaTableExists($db,$driver,'vat_returns'))qaSafe($results,'الضرائب','معادلة صافي VAT',function()use($db){$n=qaCount($db,'SELECT COUNT(*) FROM vat_returns WHERE ABS(net_vat-(output_vat-input_vat+adjustment_amount))>0.01');return[$n?'fail':'pass',$n?$n.' إقرار غير متطابق حسابيًا':'كل إقرارات VAT متطابقة حسابيًا'];});
if(qaTableExists($db,$driver,'vat_returns'))qaSafe($results,'الضرائب','فصل إعداد واعتماد VAT',function()use($db){$n=qaCount($db,"SELECT COUNT(*) FROM vat_returns WHERE status IN ('approved','filed') AND (approved_by IS NULL OR approved_by=prepared_by)");return[$n?'fail':'pass',$n?$n.' إقرار يخالف الاعتماد المزدوج':'كل الإقرارات المعتمدة تحقق فصل المهام'];});
if(qaTableExists($db,$driver,'withholding_tax_entries'))qaSafe($results,'الضرائب','احتساب ضريبة الاستقطاع',function()use($db){$n=qaCount($db,'SELECT COUNT(*) FROM withholding_tax_entries WHERE ABS(tax_amount-(taxable_amount*rate_percent/100))>0.01');return[$n?'fail':'pass',$n?$n.' التزام استقطاع غير صحيح':'كل التزامات الاستقطاع محتسبة بصورة صحيحة'];});
if(qaTableExists($db,$driver,'tax_invoices'))qaSafe($results,'الإيرادات','التحصيل الزائد',function()use($db){$n=qaCount($db,'SELECT COUNT(*) FROM tax_invoices WHERE collected_amount>total_amount+0.01');return[$n?'fail':'pass',$n?$n.' فاتورة محصلة بأكثر من قيمتها':'لا يوجد تحصيل يتجاوز قيمة الفاتورة'];});
if(qaTableExists($db,$driver,'customer_claims')&&qaTableExists($db,$driver,'customer_contracts'))qaSafe($results,'العقود','تجاوز مستخلصات العملاء للعقود',function()use($db){$n=qaCount($db,"SELECT COUNT(*) FROM (SELECT cc.id FROM customer_contracts cc LEFT JOIN customer_claims cl ON cl.customer_contract_id=cc.id AND cl.status<>'rejected' GROUP BY cc.id,cc.original_value HAVING COALESCE(SUM(cl.gross_work_value),0)>cc.original_value+0.01) x");return[$n?'fail':'pass',$n?$n.' عقد متجاوز':'لا توجد مستخلصات تتجاوز قيمة العقد'];});
if(qaTableExists($db,$driver,'subcontract_claims')&&qaTableExists($db,$driver,'subcontracts'))qaSafe($results,'العقود','تجاوز مستخلصات المقاولين للعقود',function()use($db){$n=qaCount($db,"SELECT COUNT(*) FROM (SELECT sc.id FROM subcontracts sc LEFT JOIN subcontract_claims cl ON cl.subcontract_id=sc.id AND cl.status<>'rejected' GROUP BY sc.id,sc.contract_value HAVING COALESCE(SUM(cl.gross_work_value),0)>sc.contract_value+0.01) x");return[$n?'fail':'pass',$n?$n.' عقد متجاوز':'لا توجد مستخلصات تتجاوز قيمة العقد'];});
if(qaTableExists($db,$driver,'payroll_runs'))qaSafe($results,'الرواتب','المسيرات المرحلة دون قيد',function()use($db){$n=qaCount($db,"SELECT COUNT(*) FROM payroll_runs WHERE status='posted' AND journal_entry_id IS NULL");return[$n?'fail':'pass',$n?$n.' مسير دون قيد':'كل مسير مرحل مرتبط بقيد'];});
if(qaTableExists($db,$driver,'employees')&&qaTableExists($db,$driver,'user_employee_links'))qaSafe($results,'الموظفون','حسابات الموظفين المرتبطة',function()use($db){$active=qaCount($db,"SELECT COUNT(*) FROM employees WHERE status IN ('active','نشط')");$linked=qaCount($db,'SELECT COUNT(*) FROM user_employee_links');return[$active&&$linked<$active?'warn':'pass',$linked.' حساب مرتبط من '.$active.' موظف نشط'];});
if(qaTableExists($db,$driver,'employees')&&App::columnExists('employees','national_id'))qaSafe($results,'الموظفون','جاهزية الدخول بالهوية',function()use($db){$n=qaCount($db,"SELECT COUNT(*) FROM employees e WHERE e.status IN ('active','نشط') AND (e.national_id IS NULL OR e.national_id='' OR e.work_email IS NULL OR e.work_email='' OR NOT EXISTS(SELECT 1 FROM user_employee_links l WHERE l.employee_id=e.id))");return[$n?'warn':'pass',$n?$n.' موظف نشط يحتاج تهيئة الهوية والبريد والحساب':'جميع الموظفين النشطين جاهزون للدخول بالهوية'];});
if(qaTableExists($db,$driver,'password_reset_tokens'))qaSafe($results,'الأمان','روابط الاستعادة المنتهية',function()use($db){$n=qaCount($db,'SELECT COUNT(*) FROM password_reset_tokens WHERE used_at IS NULL AND expires_at<CURRENT_TIMESTAMP');return[$n?'warn':'pass',$n?$n.' رابط منتهٍ يمكن تنظيفه دوريًا':'لا توجد روابط منتهية غير مستخدمة'];});
if(qaTableExists($db,$driver,'employees')&&qaTableExists($db,$driver,'employee_contracts'))qaSafe($results,'الموظفون','الموظفون دون عقد نشط',function()use($db){$n=qaCount($db,"SELECT COUNT(*) FROM employees e WHERE e.status IN ('active','نشط') AND NOT EXISTS(SELECT 1 FROM employee_contracts c WHERE c.employee_id=e.id AND c.status='active')");return[$n?'warn':'pass',$n?$n.' موظف نشط دون عقد':'كل الموظفين النشطين لديهم عقود'];});
if(qaTableExists($db,$driver,'audit_logs'))qaSafe($results,'الأمان','سجل التدقيق',function()use($db){$n=qaCount($db,'SELECT COUNT(*) FROM audit_logs');return[$n?'pass':'warn',$n.' حركة مسجلة'];});

$summary=['pass'=>0,'warn'=>0,'fail'=>0];foreach($results as $r)$summary[$r['status']]++;
if(($_GET['format']??'')==='json'){header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store');echo json_encode(['ok'=>$summary['fail']===0,'generated_at'=>date(DATE_ATOM),'version'=>$version,'summary'=>$summary,'checks'=>$results],JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT);exit;}
header('Cache-Control: no-store');
?><!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>فحص نظام سواعد</title><style>body{font-family:Tahoma,Arial;background:#eef1f4;color:#1d2935;margin:0}.wrap{max-width:1050px;margin:30px auto;padding:0 15px}.head,.card{background:#fff;border:1px solid #d9dfe5;border-radius:12px;padding:20px;margin-bottom:14px}.sum{display:flex;gap:10px;flex-wrap:wrap}.pill{padding:8px 14px;border-radius:8px;font-weight:bold}.pass{background:#e7f8ef;color:#16724a}.warn{background:#fff6dd;color:#8a6400}.fail{background:#ffe9e9;color:#a52626}table{width:100%;border-collapse:collapse;background:#fff}th,td{text-align:right;padding:11px;border-bottom:1px solid #e5e9ed}th{background:#f7f9fb}a{color:#735b16}.faint{color:#66717d;font-size:13px}@media(max-width:700px){.card{overflow:auto}table{min-width:720px}}</style></head><body><main class="wrap"><section class="head"><h1>فحص سلامة نظام سواعد</h1><p class="faint">فحص للقراءة فقط — لا ينشئ أو يعدل أو يحذف أي بيانات.</p><div class="sum"><span class="pill pass">ناجح: <?=$summary['pass']?></span><span class="pill warn">تنبيه: <?=$summary['warn']?></span><span class="pill fail">فشل: <?=$summary['fail']?></span></div><p><a href="?format=json">تنزيل/عرض التقرير بصيغة JSON</a> · <a href="app.php">العودة للنظام</a></p></section><section class="card"><table><thead><tr><th>المجموعة</th><th>الفحص</th><th>النتيجة</th><th>التفاصيل</th></tr></thead><tbody><?php foreach($results as $r):?><tr><td><?=htmlspecialchars($r['group'])?></td><td><?=htmlspecialchars($r['name'])?></td><td><span class="pill <?=$r['status']?>"><?=$r['status']==='pass'?'ناجح':($r['status']==='warn'?'تنبيه':'فشل')?></span></td><td><?=htmlspecialchars($r['detail'])?></td></tr><?php endforeach;?></tbody></table></section><p class="faint">بعد الانتهاء احذف public/system-check.php من الخادم.</p></main></body></html>
